### ISSUE TITLE
Doesn't work on 32-bit Windows

### ISSUE THREAD

**Issue by scorcher9009** [SkyTemple/skytemple#102]
An x86 version of the program would be greatly appreciated.

**Comment by VoxNiphili** [comment]
Scorcher9009 I agree.

**Comment by Parakoopa** [comment]
A nightly for 32-bit is now available for early testing. For feeback please use #beta-tester on the Discord.

**Comment by Parakoopa** [comment]
I can't get Python-Igraph to build an actual 32bit DLL for Msys2 Mingw32, so I'm kinda stuck and it doesn't work. If anyone is able to, let me know.

**Comment by Parakoopa** [comment]
Works now.
