### ISSUE TITLE
Move Shortcut Patch Occasionally Opens Up Item Menu When Pressing L+B

### ISSUE THREAD

**Issue by XModxGodX** [SkyTemple/skytemple#104]
The move shortcut patch should probably disable the item menu shortcut when holding L. Easiest to reproduce when the move assigned to B has no PP left but can also happen if you hold L and mash B fast enough even with PP left on the move.

**Comment by Parakoopa** [comment]
pinging @End45

**Comment by End45** [comment]
I'll look into this once I have some free time

**Comment by End45** [comment]
This has been fixed in my repo (https://github.com/End45/EoS-asm-hacks/commit/177f765913c5c2c10cde64510d7d38da57a048b9). Now it's up to @Parakoopa to update the files in SkyTemple.
