### ISSUE TITLE
MacOS Fatal Import error upon startup with loading gi libraries

### ISSUE THREAD

**Issue by RileSamurott** [SkyTemple/skytemple#107]
Skytemple is unable to run for me. Upon attempting to open the application by directly clicking on it, the app boots then immediately closes before displaying anything. Trying to run it using `pre_run_skytemple` outputs this log:
```Traceback (most recent call last):
  File "main.py", line 21, in <module>
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "gi/__init__.py", line 40, in <module>
ImportError: dlopen(/Applications/SkyTemple.app/Contents/MacOS/gi/_gi.cpython-38-darwin.so, 2): Symbol not found: _objc_opt_class
  Referenced from: /Applications/SkyTemple.app/Contents/MacOS/gi/../libgio-2.0.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
 in /Applications/SkyTemple.app/Contents/MacOS/gi/../libgio-2.0.0.dylib
[42601] Failed to execute script main
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...9 completed.

[Process completed]
```

It is very much worth noting that I run a 2017 Macbook Pro on Mojave 10.14.6. I reckon this is just a version error, and if it is and Skytemple can only run on Catalina at the moment, can somebody change the Project Pokemon download page to indicate incompatibility with 10.14, which is Mojave?

**Comment by tech-ticks** [comment]
Sorry, we got the names mixed up... It's supposed to say Catalina instead of Mojave since that's how 10.15 is called. We're only supporting 10.15 right now since that's the version we can test and create automatic builds on.
