### ISSUE TITLE
Dungeon layout unk hidden stairs research 

### ISSUE THREAD

**Issue by TenmaRH** [SkyTemple/skytemple#113]
0 --> 100% secret bazaar
1 --> 100% secret room
255 --> 50% secret bazaar, 50% secret room
Other values: 0% secret bazaar, 0% secret room (you just go to the next floor like normal stairs)

I tested this with 100% chance hidden stairs beach cave floor 1
10 tests with 0,1,255
3 tests with 2,3,4,8,10,15,16,17,32,64,112,127,128,129,196,253,254

**Comment by Parakoopa** [comment]
Thanks!
