### ISSUE TITLE
SpriteCollab portrait downloader

### ISSUE THREAD

**Issue by theCapypara** [SkyTemple/skytemple#123]
Add a downloader for portraits to the portrait editor

---
Beep, boop, I'm [a bot](https://github.com/Parakoopa/IssueBot)! This issue was created by `@Parakoopa` in `#skytemple`.

**Comment by riiswa** [comment]
It's about adding a button on each portrait to be able to download it?  (Like the new delete button)

**Comment by Parakoopa** [comment]
Hm, I'd add one button that maybe opens a dialog? You'd also need to be able to select the form and probably a preview.
Also, the "backend logic" for this is already in the randomizer (for reference):
https://github.com/SkyTemple/skytemple-randomizer/blob/master/skytemple_randomizer/randomizer/portrait_downloader.py#L70

**Comment by theCapypara** [comment]
This is done.
