### ISSUE TITLE
Fixed floor settings, unk values

### ISSUE THREAD

**Issue by Parakoopa** [SkyTemple/skytemple#127]
Also, I did some research about fixed floor flag properties, and if set to 1:
- byte 4 disables the darkness level
- byte 5 seems to affect some traps (like Pitfall trap or Pokémon trap won't work)
- byte 8 seems to disable all kind of warp effects (that includes the Warp trap, warp orbs, but also the Gust trap or the effect of the Roar move)
- byte 9 prevents from pulling items like with the Trawl Orb; this is used in "puzzle" rooms to prevent using this to pull the items you are supposed to get by solving the "puzzle"

---
Beep, boop, I'm [a bot](https://github.com/Parakoopa/IssueBot)! This issue was created by `@Irdkwia` in `#reverse-engineering`.

**Comment by End45** [comment]
I have updated the dungeon data document with the details about each field and the exact values that enable/disable each of the settings: https://docs.google.com/document/d/1UfiFz4xAPtGd-1X2JNE0Jy2z-BLkze1PE4Fo9u-QeYo/edit#heading=h.x9xbfsm2wtin
