### ISSUE TITLE
[Feature request] Allow for mass-export of Pokémon data

### ISSUE THREAD

**Issue by mk360** [SkyTemple/skytemple#130]
Currently we can only export Pokémon data one by one. I believe it would be a nice addition to allow the user to export all Pokémon's data (all species, all genders, all tabs) at once.

**Comment by Parakoopa** [comment]
Whoops, referenced the wrong issue in the commit.

**Comment by mk360** [comment]
Hey there, are there any updates for this issue?

**Comment by theCapypara** [comment]
I'll plan this for next release, but no promises.
