### ISSUE TITLE
Add help buttons to monster editing

### ISSUE THREAD

**Issue by Parakoopa** [SkyTemple/skytemple#151]
Please comment possible help texts under this issue

---
Beep, boop, I'm [a bot](https://github.com/Parakoopa/IssueBot)! This issue was created by `@Parakoopa` in `#skytemple`.

**Comment by End45** [comment]
Weight: Affects the damage the pokémon takes when attacked with Grass Knot
Size: Affects the damage the pokémon takes when attacked with a Sizebust orb
Recruit rates: If you answered yes to the question asking if you played EoT or EoD in the personality test and you haven't recruited this pokémon yet, the second recruit rate is used instead. If you have recruited this pokémon already, its recruit rate is halved (only if it's positive).
Unk21h: If the current SCENARIO_BALANCE_FLAG value is lower than this number, the pokémon won't spawn in dungeons.
