### ISSUE TITLE
Crash when selecting items in GtkCellRendererCombos

### ISSUE THREAD

**Issue by theCapypara** [SkyTemple/skytemple#293]
Also affects 1.2.3., downgrade/upgrade Gtk?

---
Beep, boop, I'm [a bot](https://github.com/Parakoopa/IssueBot)! This issue was created by `@Parakoopa` in `#beta-tester`.

**Comment by Parakoopa** [comment]
Seems to be Windows only. Check if just frozen App?

**Comment by Parakoopa** [comment]
Seems to go back to a 1.1.5 beta.

**Comment by theCapypara** [comment]
Should be fixed.
