### ISSUE TITLE
Error when installing on Windows

### ISSUE THREAD

**Issue by AeonCaptain** [SkyTemple/skytemple#3]
Does the app support windows? I get this error during installation while running:
"python -m pip install git+https://github.com/SkyTemple/skytemple.git"

This is the error while installing dependencies:

Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\fang2\AppData\Local\Programs\Python\Python37\python.exe' 'C:\Users\fang2\AppData\Local\Programs\Python\Python37\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\fang2\AppData\Local\Temp\pip-build-env-fieyk3bx\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel pycairo
       cwd: None
  Complete output (34 lines):
  Collecting setuptools
    Using cached setuptools-47.1.1-py3-none-any.whl (583 kB)
  Collecting wheel
    Using cached wheel-0.34.2-py2.py3-none-any.whl (26 kB)
  Collecting pycairo
    Using cached pycairo-1.19.1.tar.gz (205 kB)
  Using legacy setup.py install for pycairo, since package 'wheel' is not installed.
  Installing collected packages: setuptools, wheel, pycairo
      Running setup.py install for pycairo: started
      Running setup.py install for pycairo: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'C:\Users\fang2\AppData\Local\Programs\Python\Python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\fang2\\AppData\\Local\\Temp\\pip-install-lnkcurhg\\pycairo\\setup.py'"'"'; __file__='"'"'C:\\Users\\fang2\\AppData\\Local\\Temp\\pip-install-lnkcurhg\\pycairo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\fang2\AppData\Local\Temp\pip-record-793490ak\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\fang2\AppData\Local\Temp\pip-build-env-fieyk3bx\overlay' --compile --install-headers 'C:\Users\fang2\AppData\Local\Temp\pip-build-env-fieyk3bx\overlay\Include\pycairo'
           cwd: C:\Users\fang2\AppData\Local\Temp\pip-install-lnkcurhg\pycairo\
      Complete output (18 lines):
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.7
      creating build\lib.win-amd64-3.7\cairo
      copying cairo\__init__.py -> build\lib.win-amd64-3.7\cairo
      copying cairo\__init__.pyi -> build\lib.win-amd64-3.7\cairo
      copying cairo\py.typed -> build\lib.win-amd64-3.7\cairo
      running build_ext
      building 'cairo._cairo' extension
      creating build\temp.win-amd64-3.7
      creating build\temp.win-amd64-3.7\Release
      creating build\temp.win-amd64-3.7\Release\cairo
      C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=19 -DPYCAIRO_VERSION_MICRO=1 -IC:\Users\fang2\AppData\Local\Programs\Python\Python37\include -IC:\Users\fang2\AppData\Local\Programs\Python\Python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tccairo/device.c /Fobuild\temp.win-amd64-3.7\Release\cairo/device.obj
      device.c
      C:\Users\fang2\AppData\Local\Temp\pip-install-lnkcurhg\pycairo\cairo\pycairo.h(37): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'C:\Users\fang2\AppData\Local\Programs\Python\Python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\fang2\\AppData\\Local\\Temp\\pip-install-lnkcurhg\\pycairo\\setup.py'"'"'; __file__='"'"'C:\\Users\\fang2\\AppData\\Local\\Temp\\pip-install-lnkcurhg\\pycairo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\fang2\AppData\Local\Temp\pip-record-793490ak\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\fang2\AppData\Local\Temp\pip-build-env-fieyk3bx\overlay' --compile --install-headers 'C:\Users\fang2\AppData\Local\Temp\pip-build-env-fieyk3bx\overlay\Include\pycairo' Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\fang2\AppData\Local\Programs\Python\Python37\python.exe' 'C:\Users\fang2\AppData\Local\Programs\Python\Python37\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\fang2\AppData\Local\Temp\pip-build-env-fieyk3bx\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel pycairo Check the logs for full command output.

**Comment by AeonCaptain** [comment]
Needs Mingw msys2 python

**Comment by Parakoopa** [comment]
I added a guide for building on Windows ("BUILDING_WINDOWS.md")
