### ISSUE TITLE
Windows: font aliasing issue

### ISSUE THREAD

**Issue by theCapypara** [SkyTemple/skytemple#34]
Maybe this is me, but the font antialiasing/cleartype makes it *much* harder to read

---
Beep, boop, I'm [a bot](https://github.com/Parakoopa/IssueBot)! This issue was created by `@MandL27` in `#skytemple-tester`.

**Comment by MandL27** [comment]
Image since the bot didn't crosspost it:
![image](https://user-images.githubusercontent.com/10366615/93132714-20961e80-f6a4-11ea-854b-1a6f4050ca80.png)

**Comment by theCapypara** [comment]
Should be fixed with the new GTK integeration, otherwise feel free to re-open.
