### ISSUE TITLE
Editing fixed rooms and reloading the ROM throws multiple errors

### ISSUE THREAD

**Issue by End45** [SkyTemple/skytemple#341]
https://discord.com/channels/710190644152369162/712341699292037121/890376305005187122
> so I've noticed some things when editing fixed rooms. first of all, SkyTemple always marks them when an asterisk (*) - as if there were unsaved changes in that room - once you stop editing the room, even if you didn't make any changes. regardless if you make changes, reloading the ROM (saving or not) causes these errors on startup

**Comment by theCapypara** [comment]
This is fixed.in 1.5.2.
