### ISSUE TITLE
Add auto crediting system for sprites and portraits

### ISSUE THREAD

**Issue by emboarger** [SkyTemple/skytemple#354]
The PNG format supports embedding certain texts as shown in the documentation here: [https://www.w3.org/TR/PNG/#11textinfo](url)

Use this feature to embed the creators of the sprites and portraits into the png files itself (when the files get uploaded to spritebot embed it so may need collaboration with audino to do this with spritebot). Then when importing the portraits and sprites to skytemple, it automatically grabs the embedded creators and adds them to the credits at the end of the game. Add a check when importing so the same creators don't get added twice.

**Comment by theCapypara** [comment]
I'll probably not support what was proposed in this issue (if you want SpriteBot to support embeding metadata, please open an issue at https://github.com/PMDCollab/SpriteBot; if it gets implemented I might reconsider supporting this)

However I am currently working on implementing SpriteCollab support directly into SkyTemple and will also see how I can add auto-credits to the game.
