### ISSUE TITLE
Automatically set indices for sprite animations

### ISSUE THREAD

**Issue by emboarger** [SkyTemple/skytemple#355]
Make it so the creator of a sprite does not need to add index values for each animation and automatically apply a predetermined index when imported.

**Comment by End45** [comment]
I think this should only be done for empty index values, or only if the user confirms that they want to auto-fill the indexes. This way it will always be possible to manually set the numbers, which you might want to do since only certain indexes can be accessed using `SetAnimation()`.

**Comment by emboarger** [comment]
Yeah that's a good idea. Maybe just auto-assign indices that need to be a specific value and ignore what the spriter's put for it. Like attack and idle so they can't be incorrectly added in the first place. And then auto-assign the remaining if an index cannot be found. That way the spriters who make them don't have to put anything but the rom hack creators can put whatever they want to use SetAnimation() as you said

**Comment by theCapypara** [comment]
This should be done in SkyTemple 1.5.
