### ISSUE TITLE
Idle Animation Patch Messes Up Pokemon Imports

### ISSUE THREAD

**Issue by XModxGodX** [SkyTemple/skytemple#371]
Haven't tried it without the patch applied on the beta builds but importing or even copying a pokemon to another slot results in an error. I know it's the Animation patch because removing the line from the XML of the idle animation state from both gender variations makes it import just fine.
![Screenshot 2021-12-19 221809](https://user-images.githubusercontent.com/22751086/146836307-acaf6304-99fc-4c9a-8002-7f4e1f7f1f35.png)

**Comment by theCapypara** [comment]
This should be fixed, feel free to re-open if not.
