### ISSUE TITLE
Performer deletion error

### ISSUE THREAD

**Issue by sudzoof** [SkyTemple/skytemple#372]
Deleting performers deletes the wrong one, which causes problems when you click on the one that wasn't deleted on the scene and try to delete it.
![unknown](https://user-images.githubusercontent.com/60050712/146839413-a85f37cc-cc1d-46a9-be44-f53d95f7f01d.png)

**Comment by theCapypara** [comment]
Hi, is this still an issue in the newest nightly?

**Comment by theCapypara** [comment]
I was able to reproduce this, will be fixed in next release.
