### ISSUE TITLE
Missing File Extension in Item and Trap Export

### ISSUE THREAD

**Issue by Adex-8x** [SkyTemple/skytemple#389]
Selecting the Export option for both Item and Trap sprites will not save the image unless the user adds their own ".png" extension to the file. It also gives the following error:
<img width="521" alt="item_and_trap_error" src="https://user-images.githubusercontent.com/91418697/156236687-0e3081b2-629c-49cd-bbae-3885691ae893.png">

**Comment by theCapypara** [comment]
Oh boy. The issue is that my code is flawed, this happens in every save dialog whenever any part of the path (!) contains a ".".

**Comment by theCapypara** [comment]
@Adex-8x Can you confirm this error does not pop up when the path doesn't contain a .?
