### ISSUE TITLE
Sometimes skytemple doesn't show a window but is visible in task manager

### ISSUE THREAD

**Issue by Emboarger** [SkyTemple/skytemple#442]
Sometimes when I go to open SkyTemple it doesn't open properly but instead appears in task manager without showing any window. It seems to happen more often when I've previously hibernated my pc and works again after restarting. It has happened on both laptop's I've owned since using it (both Windows).

The only line in the log file is: 
skytemple_files.dungeon_data.mappa_bin.item_list - WARNING - MappaItemCategory is deprecated. Use Pmd2DungeonData's item_categories attribute instead. This deprecated class will provide dynamically generated values from the default EU XML configuration.

**Comment by marius851000** [comment]
I also ocasionally have situation when SkyTemple is stuck on startup when behind a captive portal. It seems to be related to the Discord library. The window open after pressing Ctrl+C in the terminal (and it then print an error message about Discord).

Suggestion of improvement : initialize Discord in the background (idk I'm not familiar with this library)

19 juil. 2022 21:15:45 emboarger ***@***.***>:

**Comment by theCapypara** [comment]
Hi! Which version were you on when this issue happened?

**Comment by emboarger** [comment]
I think I first noticed it in 1.3.6 but have had it in all versions since

**Comment by theCapypara** [comment]
Do you still have this issue with SkyTemple 1.5. ?

**Comment by emboarger** [comment]
Sorry, I haven't been properly active in ages so haven't been using ST since 1.4

**Comment by Emboarger** [comment]
Been doing some testing and it appears to be fixed now
