### ISSUE TITLE
Items with IDs between 1352 and 1399 cannot be placed on fixed rooms

### ISSUE THREAD

**Issue by End45** [SkyTemple/skytemple#453]
Originally reported at https://discord.com/channels/710190644152369162/712341752111169707/1011405803481219092
The item table used by fixed rooms doesn't allow specifying items with IDs between 1352 and 1399. Those items are normally invalid, but they can be edited into being usable.

I tried changing the following constant to 1400, but it didn't seem to have an effect:
https://github.com/SkyTemple/skytemple/blob/db295d0291bf3ad0a6131c39ae84455615c8ba7e/skytemple/module/dungeon/__init__.py#L21

**Comment by theCapypara** [comment]
I don't remember the details right now, but iirc the way that entities in fixed rooms are encoded its not possible to place these items.

**Comment by theCapypara** [comment]
Actually read through the docs again, the limitation was on some entity spawn entries. For item IDs everything should work.

**Comment by theCapypara** [comment]
Oh! I remember again. The game treats entries above 1352 special, at least the next 100 items. So I don't think this would work.

**Comment by End45** [comment]
From what I've seen, the game treats entries with IDs >= 1400 as special, but 1352-1399 are treated like normal items. I just tested this by forcing the game to place item 1352 on a fixed room after turning it into a valid item and it worked perfectly.

**Comment by theCapypara** [comment]
In that case this check is wrong:
https://github.com/SkyTemple/skytemple/blob/master/skytemple/module/dungeon/controller/fixed_rooms.py#L70

That's probably why changing the constant didn't work for you.
