### ISSUE TITLE
Fixed rooms: Trying to display a special item throws an error

### ISSUE THREAD

**Issue by End45** [SkyTemple/skytemple#506]
Originally reported at https://discord.com/channels/710190644152369162/1070737226733993984

Every time SkyTemple tries to render a special item in a fixed room, an error like the following is thrown, sometimes multiple times at once:
```
CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "C:/msys64\home\main\skytemple/skytemple/module/dungeon/fixed_room_drawer.py", line 221, in draw
    self._draw_action(ctx, action, sx, sy)
  File "C:/msys64\home\main\skytemple/skytemple/module/dungeon/fixed_room_drawer.py", line 424, in _draw_action
    self.entity_renderer.draw_action(ctx, action, sx, sy)
  File "C:/msys64\home\main\skytemple/skytemple/module/dungeon/fixed_room_entity_renderer/full_map.py", line 43, in draw_action
    self._draw_item(ctx, item.item_id, sx, sy)
  File "C:/msys64\home\main\skytemple/skytemple/module/dungeon/fixed_room_entity_renderer/full_map.py", line 147, in _draw_item
    itm = self.parent.module.get_item(item_id)
  File "C:/msys64\home\main\skytemple/skytemple/module/dungeon/module.py", line 835, in get_item
    return self.project.open_file_in_rom('BALANCE/item_p.bin', FileType.ITEM_P).item_list[idx]
pyo3_runtime.PanicException: index out of bounds: the len is 1400 but the index is 1400
```

The cause seems to be the following line: https://github.com/SkyTemple/skytemple/blob/b18408efe116130e2b89980aa2b2af9c53cf467c/skytemple/module/dungeon/fixed_room_entity_renderer/full_map.py#L44
It expects an `IndexError` when trying to draw a special item (since those use IDs past the last valid item ID), but as seen in the stack trace, a `PanicException` is thrown instead, which is never caught.
This is probably related to the recent switch to multithreading when performing some operations (that was changed recently, right?).

**Comment by theCapypara** [comment]
The reason for this is, that the error occurs in Rust code now. Disabling native file handlers is a workaround. The check probably needs to be rewritten, possibly an interface function added to do this check instead.

**Comment by End45** [comment]
Looks like the problem still happens in the latest dev version. Fixed room 165 is an example.

**Comment by theCapypara** [comment]
Huh https://github.com/SkyTemple/skytemple/commit/632f0c059e31405542774d89f75831fc7cb911f6 should have fixed it. I wasn't able to reproduce it myself.
I guess `item_count` somehow returns the wrong number of items?
