### ISSUE TITLE
Weird pokemon icons

### ISSUE THREAD

**Issue by Brianette** [SkyTemple/skytemple#529]
Hello, I'm new here and loving this project.
For my firsts seeds pokemon were normal with normal icons but since this morning I tried a lot of things and can only generate weird pokemon icon (like plushies, drawings), I get it might be a joke or smthing but how can I remove it to play with normal pokemons ? 
Thanks for anyone helping me !

**Comment by End45** [comment]
Happy April Fools day!

As the lead dev stated in the Discord server,
> You can force to disable this by setting your system time to any other date than April 1st or setting the environment variable SKYTEMPLE_FUN to 0

**Comment by Brianette** [comment]
Oh lol !! thank you it was purely random luck that I ran it today, well april fools worked on me at least !
