### ISSUE TITLE
Problem after importing a new map

### ISSUE THREAD

**Issue by Paxatz** [SkyTemple/skytemple#555]
I imported a custom map background and when I went to edit the script scenes for it (eg. the Enter or Acting scenes) SkyTemple threw up this error;

![image](https://github.com/SkyTemple/skytemple/assets/60794374/3635c894-c476-449a-bc85-91b398df2d7e)

Disabling native file handlers caused me to not be able to load the map at all, throwing up this error in the Map Backgrounds editing section

![image](https://github.com/SkyTemple/skytemple/assets/60794374/944ad9f4-e01c-48dc-be72-314d184084db)

**Comment by theCapypara** [comment]
For reference:

The issue happens when disabling the BPA of a map that normally has one.
See thread: https://canary.discord.com/channels/710190644152369162/712341699292037121/1110539600784527450

**Comment by theCapypara** [comment]
The issue is that BPAs were not properly disabled. They were disabled in the BPC file, but the change to the level list file were not properly saved.
