### ISSUE TITLE
Certain background crashes at the preview

### ISSUE THREAD

**Issue by JuanmaSG-dev** [SkyTemple/skytemple#558]
A certain 30x10 background I have seems to break the second time you visualize it. What do I mean, when you import it, you will be able to see it perfectly, reload the rom, check it again and it crashes. Happens in both the Map Backgrounds, the Script Scenes (if you add one), and at the add Position Mark preview as well. Here are both the xdelta patch with only that background on a clean US rom, and the background. Is only 1 layer.
[errorbg.zip](https://github.com/SkyTemple/skytemple/files/11712559/errorbg.zip)
![road](https://github.com/SkyTemple/skytemple/assets/129054732/4edd038f-68e1-4017-b553-ca30d13fa1c7)
![image](https://github.com/SkyTemple/skytemple/assets/129054732/57cb2a11-b5b8-4564-a7a1-6e589a88d857)

**Comment by theCapypara** [comment]
The BPL file road.bpl is corrupted. It's only 40 bytes in size. I asked for additional info on Discord:

> I suspect that the Rust implementation of the code that adds new files to the ROM is broken and corrupts the ROM, but I'm not sure.
> JuanmaSG#5668 Can you provide the exact steps and assets (eg. the original PNG file if the one in the issue isn't already it) required to replicate this issue from a clean ROM?

**Comment by theCapypara** [comment]
The issue is, that the input PNG file has only 16 colors, not 255. The Rust code does not correctly fill the palette up to 256 colors before trying to process it.

**Comment by theCapypara** [comment]
Since the input image is imported via PIL, this may be a change/bugfix in PIL that caused the change in behavior.
