### ISSUE TITLE
AddTypes Matchup Error

### ISSUE THREAD

**Issue by Espik** [SkyTemple/skytemple#576]
When the AddTypes patch is applied, Foresight, Scrappy, and other Exclusive Items do not change Normal and Fighting's type matchup against Ghost. The functionality with Miracle Eye is either unknown or untested.

**Comment by theCapypara** [comment]
I need somebody with ASM knowledge to fix that.

**Comment by Espik** [comment]
> I need somebody with ASM knowledge to fix that.

All that needs to change is replacing two "00"s with "02"s.

**Comment by theCapypara** [comment]
Then I'm happy for a PR that changes it, because I don't know where.

**Comment by theCapypara** [comment]
Fixed by Adex in https://github.com/SkyTemple/skytemple-files/pull/431
