### ISSUE TITLE
Cannot access Fixed Rooms in JP ROM

### ISSUE THREAD

**Issue by Adex-8x** [SkyTemple/skytemple#602]
When attempting to view any Fixed Room in the _Fixed Rooms_ tab, the following error displays:
<img width="557" alt="fixed_room_error" src="https://github.com/SkyTemple/skytemple/assets/91418697/48004b2b-102f-4db5-b593-0c54ffecbf82">
(Unsure if this issue should belong in `skytemple-files` instead)

**Comment by theCapypara** [comment]
That's odd.
```py
monster = self.lst_monster[entity.monster_id]
```
is the line that fails.

`lst_monster` is the monster entity list. That would mean that the entity references a monster that is out of bounds? Either one of the fixed room related symbols is wrong or the table contains an invalid entry in the JP ROM.
