### ISSUE TITLE
[JP] IQ Skills are misaligned

### ISSUE THREAD

**Issue by Laioxy** [SkyTemple/skytemple#603]
I checked by loading the JP ROM(vanilla) on Nightly version and it seems that the IQ Skills are off.
![capture](https://github.com/SkyTemple/skytemple/assets/127853491/e2683a22-f3af-4f70-8714-7f60fa5b9c11)

In the image, the IQ Skill for ID7 is "PP Checker", IQ Points is "40", Restriction Group is "7", and all groups appear to have been mastered. Originally PP Checker should be unused and IQ Points should be set to 9999 and not belong to any group.
Seeing that I haven't received any specific remarks about it so far, I think it's a JP version only phenomenon, what do you think?

**Comment by theCapypara** [comment]
This is for the NA ROM.
![grafik](https://github.com/SkyTemple/skytemple/assets/3512122/4d86f329-a5a4-4287-b86e-6e2432ffaf1e)

So 6 is not PP Checker in the JP ROM? It might be that the symbols are wrong or the text strings.

**Comment by theCapypara** [comment]
Ah what @Adex-8x said could be correct. It is specified here:
https://github.com/SkyTemple/skytemple-files/blob/master/skytemple_files/_resources/ppmdu_config/pmd2data.xml#L262
