### ISSUE TITLE
Error when exporting pokémon in 1.6 beta

### ISSUE THREAD

**Issue by End45** [SkyTemple/skytemple#619]
Originally reported at https://discord.com/channels/710190644152369162/1154063220047364147
> Hey, I have this error message when I try to export a Pokémon

https://cdn.discordapp.com/attachments/1154063220047364147/1154063220580028426/image.png

SkyTemple Version: 1.6.0b1

**Comment by theCapypara** [comment]
lol, turns out Sentry thought the same: https://github.com/SkyTemple/skytemple/pull/605#issuecomment-1728202931

**Comment by End45** [comment]
Oh, that's quite helpful lol
