### ISSUE TITLE
Can't Import Tilesets

### ISSUE THREAD

**Issue by Espik** [SkyTemple/skytemple#684]
Importing custom tilesets does not appear to work. The error message doesn't give a lot of information
![image](https://github.com/SkyTemple/skytemple/assets/47647610/ec877c5b-c5cd-4007-8942-a57a0ac9bd31)

**Comment by Espik** [comment]
I have found a temporary work-around. The tileset needs to be exported from the current version of SkyTemple for it to be imported successfully. If it was exported from an older version, it will not import.

**Comment by Espik** [comment]
Alex made a thread detailing the issue here: https://discord.com/channels/710190644152369162/712341699292037121/1186535817938751528

**Comment by theCapypara** [comment]
Solved via skytemple-dtef 1.6.
