### ISSUE TITLE
Display Sprite Size value of Pokemon in the UI (without needing to use ExpandPokeList)

### ISSUE THREAD

**Issue by AlliterativeAlias** [SkyTemple/skytemple#779]
Quoting Frostbyte:
> SkyTemple automatically calculates the sprite size when importing [a mon sprite], since the value needs to be saved to the ROM. There's no way to view said value in the UI right now though (except if ExpandPokeList is applied)

Sprite size would be useful for all users to know, regardless of whether or not they're using ExpandPokeList, in order to help them avoid problems with sprites being unexpectedly too large for entering dungeons.

Users can take advantage of knowing sprite size with the following heuristic for translating sprite size to body size, from Irdkwia:
> 1 Body Size every 6 Sprite Size, rounded to higher (e.g. 7 Sprite Size = 2 Body Size) (minimum for standard monster)

Frostbyte has documented this information in pmdsky-debug today so that it's accessible through the symbol editor: https://github.com/SkyTemple/skytemple-files/pull/524#issue-2432680349

**Comment by Frostbyte0x70** [comment]
As a reminder: The size values are normally stored in a hardcoded array in arm9.bin, but ExpandPokeList moves them to two unused fields in monster.md. When the patch is not applied, SkyTemple displays the unused values as "UnkXXX" (I don't remember the exact name), but when ExpandPokeList is applied, the UI fields are renamed to "Sprite Size" and "Sprite File Size" and display the size values.

A possible implementation is to always display the "Sprite Size" and "Sprite File Size" inputs, and internally read/write the values to the correct file and location depending on whether the patch is applied or not. If ExpandPokeList is applied, do not show the UnkXXX inputs.

**Comment by theCapypara** [comment]
Sprite size can now be edited as long as the new "SpriteSizeInMonsterData" patch is applied, see #781.
