### ISSUE TITLE
Set Body Size automatically when importing sprites

### ISSUE THREAD

**Issue by AlliterativeAlias** [SkyTemple/skytemple#788]
It would be helpful if SkyTemple could automate initial body size assignment, now that we're more aware of how body size is meant to correlate to sprite size.

Specifically, the minimal body size needed to certainly sustain a Pokemon is the smallest integer such that Body Size x 6 is equal to or higher than Sprite Size (ergo SS 6 = BS 1, SS 7-12 = BS 2, SS 13-18 = BS 3, SS 19-24 = BS 4, SS 25-30 = BS 5, SS 31-36 = BS 6).

Users can change it to whatever they might need afterwards (for example they might want it bigger), but this default would guarantee that no unexpected party size errors happen after just doing importation.

**Comment by theCapypara** [comment]
Please also take into account #789 when working on this and the overall implications of sprite size and communication of it in SkyTemple.

Ideally these settings should all be grouped and communicated together.

**Comment by theCapypara** [comment]
Some more thoughts of mine on this topic (from Discord):

> We should really move these settings to a new tab or something and streamline how they are presented and automatically generated.
> They should all be shown in a new tab and the fields for Sprite Size and Sprite File Size should be empty and grayed out if irdkwia's new patch is not applied, with a small note on why and that that patch needs to be applied
> Sprite Size should maybe be renamed to "VRAM Slot Size" (if that name is accurate!) in the UI and "Sprite File Size" to "File Block Size" or something
> Shadow Size may also go there just because it's relevant
> the new tab could be called "Sprite Size"

**Comment by theCapypara** [comment]
Closed by https://github.com/SkyTemple/skytemple-files/pull/530, #785
