### ISSUE TITLE
Put explanation boxes next to Sprite Size and Sprite File Size

### ISSUE THREAD

**Issue by AlliterativeAlias** [SkyTemple/skytemple#789]
In relation to #781, it would be helpful to put up explanation boxes next to Sprite Size and Sprite File Size to clarify how they work.
As explained by Irdkwia and Frostbyte in the discord:

- Sprite Size deals with Pokemon fitting onto the party in dungeons. The limit is 36 units of Sprite Size in total for the whole party. If this is exceeded, Pokemon from the party are cut off from spawning on the dungeon floor one by one until the sum of Sprite Size is 36 or less (but will still be counted as being on the party in the team menu).

- Sprite File Size describes the actual size of the sprite file, and deals with enemies and NPCs in dungeons (all Pokemon not on the player's party). The size in bytes of a sprite file is obtained by multiplying Sprite File Size by 512. The limit for all enemies and allied NPCs on a dungeon floor is 352 kB (704 Sprite File Size) in total, counting by species present on the floor.

**Comment by theCapypara** [comment]
See my comment: https://github.com/SkyTemple/skytemple/issues/788#issuecomment-2256225678

**Comment by theCapypara** [comment]
Closed by #785
