### ISSUE TITLE
Nightly build fails to open the ROM correctly

### ISSUE THREAD

**Issue by SergeyThePiplup** [SkyTemple/skytemple#810]
After downloading the latest Nightly build available (from build action #6600) to test the translation, I've got the following message after opening a ROM. After that message, SkyTemple seem to react like I didn't opened anything, except I can open a debugger and edit scripts. 
Platform: Windows 11.
(An error report was sent via Sentry too) 
![image](https://github.com/user-attachments/assets/b53567b5-bd66-4a24-b835-994ca598a7fa)

**Comment by SergeyThePiplup** [comment]
The traceback:
SkyTemple 1.8.3.dev0+14a367aa Error Report

```
Traceback (most recent call last):
  File "controller\main.py", line 362, in on_file_opened
  File "core\rom_project.py", line 687, in init_patch_properties
  File "skytemple_files\graphics\kao\handler.py", line 70, in properties
ImportError: cannot import name 'KaoPropertiesState' from 'skytemple_rust.st_kao' (unknown location)
```

**Comment by SergeyThePiplup** [comment]
(Same error happens on the nightly from https://download.skytemple.org/skytemple/nightly too

**Comment by Frostbyte0x70** [comment]
I can't reproduce this with the latest dev version.

**Comment by theCapypara** [comment]
I asume this is no longer an issue then, feel free to re-open otherwise.
