### ISSUE TITLE
Change response type when using the native file chooser

### ISSUE THREAD

**Issue by irdkwia** [SkyTemple/skytemple#91]
The native file chooser uses "Gtk.ResponseType.ACCEPT" as response when confirming, not "Gtk.ResponseType.OK".
Because of this, all import/export functions won't work because they test the response with "Gtk.ResponseType.OK" to confirm the action.

**Comment by irdkwia** [comment]
I'm working on that issue

**Comment by Parakoopa** [comment]
I should probably have tested actually clicking OK on these dialogs...
